version: '3.2'
services:
    mongo:
        image: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
        ports:
            - '27018:27017'
        volumes:
            - ./data:/data/db
    redis:
        image: 'redis:latest'
        ports:
            - '6380:6379'
